ftp.ftpFileDownload=FTP File Download
ftp.sftpFileUpload=SFTP File Upload
ftp.dataListSFTPUploadTool=DataList SFTP Upload Tool
ftp.id=ID
ftp.label=Label
ftp.name=Name
ftp.value=Value
ftp.dataSource=Data Source
ftp.port=Port
ftp.dataListId=DataList
ftp.dataListFilter=Filter
ftp.resultFile=Result File
ftp.sourceFile=Source File
ftp.fileName=File Name
ftp.fileFormat=File Format
ftp.fileFormat.csv=CSV
ftp.deleteTemporaryFile=Delete temp file
ftp.headerValues=Header Values
ftp.footerValues=Footer Values
ftp.skipLines=Skip lines
ftp.skipLines.desc=Skip first N row in file
ftp.fieldMapping=Field mapping
ftp.fieldMapping.description=Column number index starts from 0
ftp.strictHostKeyChecking=Strict Hostkey Checking
ftp.statusVariable=Status variable
ftp.statusWorkflowVariable=Workflow variable
ftp.statusSucceed=Status succeed
ftp.statusFailed=Status failed
ftp.defaultValues=Default values
ftp.field=Field
ftp.fileUploadField=File Upload Field
ftp.fileUploadField.desc=File will be stored in this field
ftp.colNum=Spreadsheet column number
ftp.formFieldName=Form field
ftp.valueType=Value type
ftp.text=Text
ftp.number=Number
ftp.formBinding=Form Binding
ftp.formDefId=Form
ftp.downloadResult=Download Result
ftp.columnDelimiter=Column delimiter
ftp.host=Host
ftp.username=Username
ftp.password=Password
ftp.remoteFile=Remote File
ftp.dataListFTPUploadTool=FTP Upload Tool