ftp.sftpFileUpload=SFTP File Upload
ftp.dataListSFTPUploadTool=DataList SFTP Upload Tool
ftp.id=ID
ftp.label=Label
ftp.name=Name
ftp.value=Value
ftp.dataSource=Data Source
ftp.dataListId=DataList
ftp.dataListFilter=Filter
ftp.resultFile=Result File
ftp.fileName=File Name
ftp.fileFormat=File Format
ftp.fileFormat.csv=CSV
ftp.skipLines=Skip lines
ftp.skipLines.desc=Skip first N row in file